import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="box-border">
        <div>
          <h1>ЦӨЛЖИЛТ ГЭЖ ЮУ ВЭ?</h1>
          <p>
            Байгалийн бүх амьд ба амьд бус зүй тогтлууд өөр хоорондоо харилцан
            шүтэлцээтэй оршин тогтнож байдаг. Мөн тэдгээрийн аль нэг нь
            экосистемийн голлох үүргийг гүйцэтгэж байдаг. Говийн эмзэг хөрсөнд
            бол Хармагны бут сондуул голлох үүргийг гүйцэтгэж байна. Хармагны
            бут сондуулын нөлөөгөөр амьдрах амьтад, ургамлын төлөөлөл
          </p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
